dscp: Add missing ListenTCPWithTOSLogger to dscp_other
Fixes builds of gNMI for Windows and other OSes.

ListenTCPWithTOSLogger was added in commit 30d54f1, but was not added
to dscp_other.go, which broke the build for Windows.

$ GOOS=windows go build
../../netns/nslistener.go:27:24: undefined: dscp.ListenTCPWithTOSLogger

Change-Id: I74b2def62a04713c0858fbfe00a12dc92fdb4795